### ISSUE TITLE
Set-up the Tripod action appears when machineguns take minor damage

### ISSUE THREAD

**Issue by Kauwgompje** [fparma/fp-static-weapons#17]
**Mods:**
- `@CBA_A3`
- `@FP_Static_Weapons`

**Affected weapons**
- DShKM (Minitripod and AA tripod)
- KORD (Minitripod and AA tripod)
- M2HB (Minitripod and AA tripod)
- TOW
- AGS-30

**Description:**

 When weapon tripods take low amounts of damage (3-8 hits in my tests) the Set-up the Tripod action appears, using this will respawn the weapon after which it will be broken.

 If you do not use this action the weapon will break in a short period of time (~10 seconds) during this period the weapon can still be used.

**Steps to reproduce:**
- Open editor, spawn affected weapons, damage them slightly

**Where did the issue occur?**
- Editor

**Comment by ComfyPillow** [comment]
IIRC, the "Set-up Tripod" AddAction should appear when the Weapon has been tipped over. This is a BIS AddAction that has been automatically inherited from the Parent class of the Weapon, which in most cases is something along the lines of StaticWeapon, StaticMGWeapon, StaticATWeapon , etc...

I kinda want to remove this action, since most of the time all it does is either flip the vehicle over again, or make it fly into the air.

The alternative to it would be the ACE Drag or Carry system, since it does fullfill the same use-case, in addition of transporting it around.

**Comment by Kauwgompje** [comment]
Still doesn't explain why it appears though? I've tested this with vanilla weapons and they do not display the same behaviour.

**Comment by ComfyPillow** [comment]
Dunno why it happens, but I'll remove the action from the config. it does more harm than good anyway and ACE offers a more reliable solution.

**Comment by ComfyPillow** [comment]
Commit https://github.com/fparma/fp_static_weapons/commit/9ad17e46490615102379a33726a6e6e25f3ce049 Removes the AddAction to Set up Tripod.
